[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D211", "D212", "D203", "COM812", "ISC001",
    "W391", "D", "FIX001", "FIX002", "TD003",
    "S104", "T201", "S101",
]
flake8-quotes.inline-quotes = "single"

[tool.ruff.format]
quote-style = "single"
line-ending = "lf"

[tool.ruff.lint.isort]
lines-after-imports = 2
combine-as-imports = false
